### PR TITLE
Update Intructions: Creating Pull Requests

### PR DESCRIPTION
**Pull request by le000255**
Team (@ekeminiakpan , @soji0004 , @fran0571 )!

I've updated the instructions for creating pull requests.
Please review it carefully and let me know if you have any concerns.

Kindly have this reviewed before 6:00 PM tomorrow (Oct 10).

Thank you!

### CODE REVIEW

**Comment by le000255** [comment]
Please also note that `dev-branch` will be your base (default) branch from now on. So, your reviews are necessary to keep this branch up-to-date.

**Review by le000255 — COMMENTED** [review]
I approved the changes in general. 

Any further corrections with more thorough reviews are encouraged (e.g. more typos, document format, proper headings, etc.)

**Review by soji0004 — COMMENTED** [review]
I totally agree with team.

**Review by ekeminiakpan — COMMENTED** [review]
I approve this

**Comment by le000255** [comment]
> I approve this

What's the point in approving a closed pull request?

**Pull request merged**
